apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# NOTE: This component requires secrets with the basic auth credentials!
# How you create them is up to you.
# The required secrets are:
# - ironic-credentials
# - ironic-inspector-credentials
#
# Both should contain 2 fields: username and password.
# Example:
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: ironic-credentials
# data:
#   password: <base64-encoded-password>
#   username: <base64-encoded-username>

patches:
- path: credentials_patch.yaml
