apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- certificate.yaml

patchesStrategicMerge:
- mariadb_patch.yaml

secretGenerator:
- literals:
  - password=changeme
  name: mariadb-password
  type: Opaque
