[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.16.2"
  revision = "35e52d86657aba06859dd22099bfa14faf1effb2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.16.2"
  revision = "5357c4baaf6562e4d37c9afc9fef99bd16d76a9f"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.16.2"
  revision = "a2eda9f80ab8a454a81bdde16d62a1afe5f931c0"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.16.2"
  revision = "bec269661e48cb1e5fbb0d037f356ffe9e9978a0"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.34.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  branch = "master"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.12.0"

# We need to specify fsnotify source to avoid dep panic
# https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
