apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-baremetal-operator
spec:
  template:
    spec:
      containers:
      - name: baremetal-operator
        volumeMounts:
          - name: cacert
            mountPath: "/opt/metal3/certs/ca"
            readOnly: true
      volumes:
      - name: cacert
        secret:
          secretName: ironic-cacert