# permissions for end users to view dataimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataimage-viewer-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - dataimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - dataimages/status
  verbs:
  - get
