name: E2E Fixture Test

on:
  pull_request:
    branches:
    - 'main'
    - 'release-*'
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - '.gitignore'
    - 'hack/*.sh'
    - 'LICENSE'
    - 'SECURITY_CONTACTS'
    - 'DCO'
    - 'OWNERS'

permissions: {}

jobs:
  test:
    name: e2e test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - name: Build BMO e2e Docker Image
      env:
        IMG: quay.io/metal3-io/baremetal-operator:e2e
      run: make docker

    - name: Set Up Environment and Run BMO e2e Tests
      env:
        E2E_CONF_FILE: ${{ github.workspace }}/test/e2e/config/fixture.yaml
        USE_EXISTING_CLUSTER: "false"
        GINKGO_NODES: 1
      run: make test-e2e
